import { useEffect, type ButtonHTMLAttributes, type ReactNode } from 'react';
export function Button({variant='primary',className='',...props}:ButtonHTMLAttributes<HTMLButtonElement>&{variant?:'primary'|'outline'|'light'|'text'|'danger'}){return <button className={`button button-${variant} ${className}`} {...props}/>;}
export function Arrow({diagonal=false}:{diagonal?:boolean}){return <span aria-hidden="true">{diagonal?'↗':'↗'}</span>;}
export function Leaf({className=''}:{className?:string}){return <svg className={className} width="38" height="44" viewBox="0 0 38 44" fill="none" aria-hidden="true"><path d="M18 37C2 28 3 12 31 4c5 21-1 31-13 33Z" stroke="currentColor" strokeWidth="1.5"/><path d="M8 43 27 12M16 30l-3-10M21 23l9-2" stroke="currentColor" strokeWidth="1.5"/></svg>;}
export function Modal({children,onClose,label}:{children:ReactNode;onClose:()=>void;label:string}){
 useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const handler=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const modal=document.querySelector('[role="dialog"]');const list=modal?.querySelectorAll<HTMLElement>('button,a,input,select,textarea,[tabindex="0"]');if(!list?.length)return;const first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',handler);const timer=setTimeout(()=>document.querySelector<HTMLElement>('[role="dialog"] button')?.focus(),30);return()=>{document.body.style.overflow=old;clearTimeout(timer);document.removeEventListener('keydown',handler);};},[onClose]);
 return <div className="modal-backdrop" onClick={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label={label} onClick={e=>e.stopPropagation()}><Button variant="light" className="modal-close" onClick={onClose} aria-label="Close dialog">×</Button>{children}</div></div>;
}
export function SectionHeading({eyebrow,title,children}:{eyebrow:string;title:string;children?:ReactNode}){return <div className="section-heading"><p className="eyebrow"><span/> {eyebrow}</p><h2>{title}</h2>{children}</div>;}
export function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}){return <img src={src} alt={alt} className={className} loading={priority?'eager':'lazy'} decoding="async"/>;}
